2024-07-25 18:56:32,929 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-07-25 18:56:32,929 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Configure stats pid to 62258
2024-07-25 18:56:32,929 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Loading settings from /Users/janmagnuszewski/.config/wandb/settings
2024-07-25 18:56:32,929 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Loading settings from /Users/janmagnuszewski/dev/slums-model-unitac/analysis/wandb/settings
2024-07-25 18:56:32,929 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-25 18:56:32,929 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-25 18:56:32,929 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'analysis/population.py', 'program_abspath': '/Users/janmagnuszewski/dev/slums-model-unitac/analysis/population.py', 'program': '/Users/janmagnuszewski/dev/slums-model-unitac/analysis/population.py'}
2024-07-25 18:56:32,929 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-25 18:56:32,929 INFO    MainThread:62258 [wandb_init.py:_log_setup():520] Logging user logs to /Users/janmagnuszewski/dev/slums-model-unitac/analysis/wandb/run-20240725_185632-dk1en86f/logs/debug.log
2024-07-25 18:56:32,929 INFO    MainThread:62258 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/janmagnuszewski/dev/slums-model-unitac/analysis/wandb/run-20240725_185632-dk1en86f/logs/debug-internal.log
2024-07-25 18:56:32,929 INFO    MainThread:62258 [wandb_init.py:_jupyter_setup():466] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x4c698d490>
2024-07-25 18:56:32,930 INFO    MainThread:62258 [wandb_init.py:init():560] calling init triggers
2024-07-25 18:56:32,930 INFO    MainThread:62258 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'model': 'DLV3', 'split_index': 0, 'train_cities': 'selSS', 'batch_size': 24, 'use_deeplnafrica': True, 'atrous_rates': (12, 24, 36), 'learning_rate': 0.001, 'weight_decay': 0, 'gamma': 0.9, 'sched_step_size': 10, 'pos_weight': 2.0}
2024-07-25 18:56:32,930 INFO    MainThread:62258 [wandb_init.py:init():610] starting backend
2024-07-25 18:56:32,930 INFO    MainThread:62258 [wandb_init.py:init():614] setting up manager
2024-07-25 18:56:32,933 INFO    MainThread:62258 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-07-25 18:56:32,934 INFO    MainThread:62258 [wandb_init.py:init():622] backend started and connected
2024-07-25 18:56:32,949 INFO    MainThread:62258 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-07-25 18:56:32,949 INFO    MainThread:62258 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-07-25 18:56:32,949 INFO    MainThread:62258 [wandb_init.py:init():711] updated telemetry
2024-07-25 18:56:33,114 INFO    MainThread:62258 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-07-25 18:57:41,173 WARNING MainThread:62258 [wandb_init.py:init():1175] interrupted
Traceback (most recent call last):
  File "/opt/miniconda3/envs/rv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
           ^^^^^^^^^
  File "/opt/miniconda3/envs/rv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 747, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/rv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/rv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/rv/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/rv/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/rv/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-07-25 19:00:41,584 INFO    MainThread:62258 [wandb_settings.py:_apply_login():1911] Applying login settings: {}
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Current SDK version is 0.17.1
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Configure stats pid to 62258
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Loading settings from /Users/janmagnuszewski/.config/wandb/settings
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Loading settings from /Users/janmagnuszewski/dev/slums-model-unitac/analysis/wandb/settings
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'analysis/population.py', 'program_abspath': '/Users/janmagnuszewski/dev/slums-model-unitac/analysis/population.py', 'program': '/Users/janmagnuszewski/dev/slums-model-unitac/analysis/population.py'}
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_init.py:_log_setup():520] Logging user logs to /Users/janmagnuszewski/dev/slums-model-unitac/analysis/wandb/run-20240725_190041-ymd4ohgf/logs/debug.log
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/janmagnuszewski/dev/slums-model-unitac/analysis/wandb/run-20240725_190041-ymd4ohgf/logs/debug-internal.log
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_init.py:init():560] calling init triggers
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'model': 'DLV3', 'split_index': 0, 'train_cities': 'selSJ', 'batch_size': 24, 'use_deeplnafrica': True, 'atrous_rates': (12, 24, 36), 'learning_rate': 0.001, 'weight_decay': 0, 'gamma': 0.9, 'sched_step_size': 10, 'pos_weight': 2.0}
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_init.py:init():610] starting backend
2024-07-25 19:00:41,590 INFO    MainThread:62258 [wandb_init.py:init():614] setting up manager
2024-07-25 19:00:41,592 INFO    MainThread:62258 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-07-25 19:00:41,593 INFO    MainThread:62258 [wandb_init.py:init():622] backend started and connected
2024-07-25 19:00:41,604 INFO    MainThread:62258 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-07-25 19:00:41,604 INFO    MainThread:62258 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-07-25 19:00:41,604 INFO    MainThread:62258 [wandb_init.py:init():711] updated telemetry
2024-07-25 19:00:41,642 INFO    MainThread:62258 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-07-25 19:02:12,065 ERROR   MainThread:62258 [wandb_init.py:init():770] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-07-25 19:02:12,068 ERROR   MainThread:62258 [wandb_init.py:init():1181] error in wandb.init()
Traceback (most recent call last):
  File "/opt/miniconda3/envs/rv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
           ^^^^^^^^^
  File "/opt/miniconda3/envs/rv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
